:commit_author_email:
  :enabled: true
  :severity: :error
:commit_author_name_capitalization:
  :enabled: false
:commit_author_name_parts:
  :enabled: false
:commit_body_bullet:
  :enabled: true
  :severity: :warn
  :blacklist:
    - "\\*"
    - "•"
:commit_body_bullet_capitalization:
  :enabled: false
:commit_body_issue_tracker_link:
  :enabled: false
:commit_body_leading_line:
  :enabled: true
  :severity: :error
:commit_body_leading_space:
  :enabled: false
:commit_body_line_length:
  :enabled: true
  :severity: :warn
  :length: 72
:commit_body_paragraph_capitalization:
  :enabled: false
:commit_body_phrase:
  :enabled: true
  :severity: :warn
  :blacklist:
    - obviously
    - basically
    - simply
    - of course
    - everyone knows
    - easy
:commit_body_presence:
  :enabled: true
  :severity: :error
  :minimum: 1
:commit_body_single_bullet:
  :enabled: false
:commit_subject_length:
  :enabled: true
  :severity: :error
  :length: 60
:commit_subject_prefix:
  :enabled: true
  :severity: :error
  :whitelist:
    - Add
    - Change
    - Complete
    - Configure
    - Create
    - Delete
    - Disable
    - Document
    - Enable
    - Fix
    - Improve
    - Join
    - Make
    - Modify
    - Move
    - Refactor
    - Relax
    - Remove
    - Split
    - Use
    - Update
:commit_subject_suffix:
  :enabled: false
